services:
  db:
    image: postgres:16
    env_file:
      - .env
    networks:
      - network
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

networks:
  network:
    driver: bridge

volumes:
  db_data:
